version: 2.1
executors:
  node:
    parameters:
      node:
        type: string
        default: '12'
      mongodb:
        type: string
        default: '4.0.26'
    docker:
      - image: circleci/node:<< parameters.node >>
      - image: circleci/mariadb:10.3
        environment:
          MYSQL_DATABASE: urungi_tests
          MYSQL_USER: urungi
          MYSQL_PASSWORD: urungi
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_DB: urungi_tests
          POSTGRES_USER: urungi
          POSTGRES_PASSWORD: urungi
    working_directory: ~/urungi
    environment:
      MONGOMS_VERSION: << parameters.mongodb >>
      URUNGI_TEST_MYSQL: '{ "host": "localhost", "database": "urungi_tests", "user": "urungi", "password": "urungi" }'
      URUNGI_TEST_PG: '{ "host": "localhost", "database": "urungi_tests", "user": "urungi", "password": "urungi" }'

jobs:
  test:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    steps:
      - checkout
      - run: npm ci
      - run: npm test -- --maxWorkers 1 --coverage
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test:
    jobs:
      - test:
          name: node:12 mongodb:4.0
          e:
            name: node
            node: '12'
            mongodb: '4.0.26'
      - test:
          name: node:12 mongodb:4.2
          e:
            name: node
            node: '12'
            mongodb: '4.2.15'
      - test:
          name: node:12 mongodb:4.4
          e:
            name: node
            node: '12'
            mongodb: '4.4.8'
      - test:
          name: node:12 mongodb:5.0
          e:
            name: node
            node: '12'
            mongodb: '5.0.2'
      - test:
          name: node:14 mongodb:4.0
          e:
            name: node
            node: '14'
            mongodb: '4.0.26'
      - test:
          name: node:14 mongodb:4.2
          e:
            name: node
            node: '14'
            mongodb: '4.2.15'
      - test:
          name: node:14 mongodb:4.4
          e:
            name: node
            node: '14'
            mongodb: '4.4.8'
      - test:
          name: node:14 mongodb:5.0
          e:
            name: node
            node: '14'
            mongodb: '5.0.2'
      - test:
          name: node:16 mongodb:4.2
          e:
            name: node
            node: '16'
            mongodb: '4.2.15'
      - test:
          name: node:16 mongodb:4.4
          e:
            name: node
            node: '16'
            mongodb: '4.4.8'
      - test:
          name: node:16 mongodb:5.0
          e:
            name: node
            node: '16'
            mongodb: '5.0.2'
